### ISSUE TITLE
Benchmark result Reproduction

### ISSUE THREAD

**Issue by ljch2018** [INK-USC/DS-RelationExtraction#19]
I use the default setting for KBP dataset.
```
code/Model/retype/retype -data $Data -mode j -size 50 -negative 3 -threads 3 -alpha 0.0001 -samples 1 -iters 400 -lr 0.02 -transWeight 1.0
```
But my best F1 core only reach 0.31, which is far from benchmark performance(o.369).
```
My Result:
Best threshold: 0.54 .  Precision: 0.303225806442 .     Recall: 0.33215547702 . F1: 0.317032035472

Benchmark performance:
CoType (Ren et al., 2017) | 0.348 | 0.406 | 0.369
```
Would anyone help me to reproduce the  benchmark result? Thank you very much.

**Comment by shanzhenren** [comment]
hi @ljch2018 !  Since the code (and in our exp) we didn't fix the random seeds for embedding initialization, could you do multiple train/test runs and let me know the range of F1 scores you got? In our reported results we were using the max F1 from K=10 runs. Thanks!
