### ISSUE TITLE
It was fine untill “learn Cotype embeddings”

### ISSUE THREAD

**Issue by johnarchie1** [INK-USC/DS-RelationExtraction#21]
Learn CoType embeddings...
./run.sh: line 20: code/Model/retype/retype: Permission denied

**Comment by shanzhenren** [comment]
hi @johnarchie1, I think you might want to re-make the binary file to resolve the permission issue. Let me know if this works.

**Comment by bjainvarsha** [comment]
Hey!
I was trying to run the code and I got stuck at the same point - 
Learn CoType embeddings...
code/Model/retype/retype: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
-----------------------------------------------------------------------------------------------------------------------------------------

I tried installing the GSL library using the below command - 
sudo apt-get install libgsl-dev

But, I'm still getting the same error.
I'm unable to find any relevant fixes for this online as well.
